### ISSUE TITLE
Error while Run on Android device

### ISSUE THREAD

**Issue by Ahmadrezagh** [serkandyck/flutter_vpn_example#2]
I configured my own iKev2 on model then I tried to run on android
![Screenshot (133)](https://user-images.githubusercontent.com/32796161/67141242-4c2f3f80-f26e-11e9-8f32-67b26b3baf73.png)

**Comment by serkandyck** [comment]
Because flutter and library and flutter vpn plugin old version, i upgrade these library and flutter soon

**Comment by serkandyck** [comment]
@Ahmadrezagh i'm update all depency and remove google products depency, can you try again ?
