### ISSUE TITLE
Error while run ios device

### ISSUE THREAD

**Issue by a8thunder** [serkandyck/flutter_vpn_example#4]
`flutter_vpn` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

Error running pod install

**Comment by serkandyck** [comment]
Hello, im update all depencies and remove google products, can you try again ?
