### ISSUE TITLE
Can't Connect

### ISSUE THREAD

**Issue by arisawali2014** [serkandyck/flutter_vpn_example#5]
i setup my own vpn server with ikev2 strongswan, but i still can't connect it because i don't know how to insert the cert.

how to add the cert into the app?

**Comment by barahijawi** [comment]
did you find a solution?

**Comment by serkandyck** [comment]
Hello guys, i'm following this tutorial https://github.com/jawj/IKEv2-setup
The VPN server identifies itself with a Let's Encrypt certificate, so there's no need for clients to install private certificates — they can simply authenticate with username and strong password (EAP-MSCHAPv2).
